services:
  app:
    container_name: sandol-discord-bot-app
    build: .
    restart: always
    env_file:
      - .env
    networks:
      - sandol-network

networks:
  sandol-network:
    driver: bridge

volumes:
  db_data:
